"""
AI Assistant — Ask questions about sales, stock, customers, etc.
Answers are generated by an LLM using the same data that powers
the existing dashboard (via db/queries.py and data_loader.py).
"""
from __future__ import annotations

import streamlit as st

from auth.ui import require_login_and_company
from config import is_ai_enabled
from ml.qa_adapter import answer_question


require_login_and_company("AI Assistant")

st.title("AI Assistant")
st.markdown(
    """
    Ask natural-language questions about your restaurant data
    (sales, stock movement, customers, GST, sessions, etc.).

    Responses are generated by an AI model using summaries of the
    same data that powers this dashboard. If the data is insufficient
    to answer a question, the assistant will say so.
    """
)

if not is_ai_enabled():
    st.info(
        "The AI assistant is currently disabled. "
        "Set `OPENAI_API_KEY` in your `.env` file and restart the app to enable it."
    )
    st.stop()


# ── Conversation state (in-memory, per browser session) ─────────────────────
if "ai_conversations" not in st.session_state:
    # Backwards compatibility: migrate any flat history if present
    legacy = st.session_state.get("ai_history", [])
    st.session_state["ai_conversations"] = {
        0: {
            "title": "Chat 1" if not legacy else "Conversation 1",
            "messages": legacy or [],
        }
    }
    st.session_state["ai_active_conv_id"] = 0

conversations = st.session_state["ai_conversations"]
active_id = st.session_state.get("ai_active_conv_id", 0)

# Main layout: left = conversations, right = chat (ChatGPT-like)
conv_col, chat_col = st.columns([0.3, 0.7])

with conv_col:
    st.markdown("#### Conversations")
    ids = list(conversations.keys())
    if not ids:
        conversations[0] = {"title": "Chat 1", "messages": []}
        ids = [0]

    if active_id not in ids:
        active_id = ids[0]

    def _label(cid: int) -> str:
        title = conversations[cid].get("title") or f"Chat {cid + 1}"
        return title

    # Show conversations as buttons stacked vertically
    for cid in ids:
        label = _label(cid)
        cols_row = st.columns([0.8, 0.2])
        if cols_row[0].button(label, key=f"conv_{cid}"):
            active_id = cid
            st.session_state["ai_active_conv_id"] = active_id
            st.rerun()
        # Small delete button per conversation (except when there is only one)
        if len(ids) > 1:
            if cols_row[1].button("✕", key=f"del_{cid}"):
                # Delete this conversation
                conversations.pop(cid, None)
                # Adjust active id
                remaining_ids = list(conversations.keys())
                if remaining_ids:
                    st.session_state["ai_active_conv_id"] = remaining_ids[0]
                else:
                    conversations[0] = {"title": "New chat", "messages": []}
                    st.session_state["ai_active_conv_id"] = 0
                st.session_state["ai_conversations"] = conversations
                st.rerun()

    if st.button("+ New chat"):
        new_id = max(conversations.keys()) + 1 if conversations else 0
        conversations[new_id] = {"title": f"Chat {new_id + 1}", "messages": []}
        st.session_state["ai_active_conv_id"] = new_id
        st.session_state["ai_conversations"] = conversations
        st.rerun()

current_conv = conversations[active_id]
messages = current_conv["messages"]

with chat_col:
    # Render existing messages (chat-style)
    for msg in messages:
        role = msg.get("role", "assistant")
        content = msg.get("content", "")
        if hasattr(st, "chat_message"):
            with st.chat_message("user" if role == "user" else "assistant"):
                st.markdown(content)
        else:
            if role == "user":
                st.markdown(f"**You:** {content}")
            else:
                st.markdown(f"**Assistant:** {content}")

    # Starter questions
    st.markdown("#### Quick questions")
    starter_questions = [
        "What were my top 5 selling items this week?",
        "Which shop had the highest revenue yesterday?",
        "Show me dish-wise profit and loss for the last 7 days.",
        "Which customers are the most frequent visitors?",
        "Summarize stock in vs stock out for the last 30 days.",
        "How much GST did we collect last month?",
    ]
    cols = st.columns(3)
    starter_clicked = None
    for i, q in enumerate(starter_questions):
        if cols[i % 3].button(q, key=f"starter_{i}"):
            starter_clicked = q

    # Input box for new question (or starter)
    question = starter_clicked
    if question is None:
        if hasattr(st, "chat_input"):
            question = st.chat_input("Ask a question about your data")
        else:
            question = st.text_input("Ask a question about your data")

    if question:
        # Append user message to current conversation
        messages.append({"role": "user", "content": question})

        with st.spinner("Thinking..."):
            answer = answer_question(question)

        messages.append({"role": "assistant", "content": answer})

        # Set a title from the first user question if still default
        if not current_conv.get("title") or current_conv["title"] == "New chat":
            current_conv["title"] = (question[:60] + "…") if len(question) > 60 else question

        # Persist back into session state
        current_conv["messages"] = messages
        conversations[active_id] = current_conv
        st.session_state["ai_conversations"] = conversations

        # Force re-render so the latest messages show above the input
        st.rerun()

